# tasks file for openhome_player

- name: Build ohNet
  ansible.builtin.shell: cd "{{ openhome_folder }}/ohNet" ; make GenAll uset4=yes ; make

- name: Build openssl
  ansible.builtin.shell: cd "{{ openhome_folder }}/openssl" ; python ./create_lib.py --platform Linux-armhf --configure --clean --build  

- name: Build ohNetGenerated
  ansible.builtin.shell:
     cmd: |
       cd "{{ openhome_folder }}/ohNetGenerated" ; mkdir -p dependencies/Linux-armhf
       cp ../ohNet/Build/Bundles/ohNet-Linux-armhf-Release.tar.gz ./dependencies/Linux-armhf/.
       cd dependencies/Linux-armhf ; tar -xzf ohNet-Linux-armhf-Release.tar.gz ; cd ../..
       make GenAll uset4=yes
       make

- name: Build ohMediaPlayer
  ansible.builtin.shell:
     cmd: |
       mkdir -p "{{ openhome_folder }}/ohPipeline/dependencies/Linux-armhf"
       mkdir -p "{{ openhome_folder }}/ohPipeline/dependencies/AnyPlatform"
       ln -s "{{ openhome_folder }}/ohWafHelpers" "{{ openhome_folder }}/ohPipeline/dependencies/AnyPlatform"
       cd "{{ openhome_folder }}/ohPipeline/."
       ./waf configure --dest-platform=Linux-armhf --ohnet=../ohNet --ssl=../openssl/build/Linux-armhf --cross=
       ./waf build
       ./waf bundle

- name: Build ohPlayer
  ansible.builtin.shell:
     cmd: |
       mkdir -p "{{ openhome_folder }}/ohPlayer/dependencies/AnyPlatform"
       ln -s "{{ openhome_folder }}/ohWafHelpers" "{{ openhome_folder }}/ohPlayer/dependencies/AnyPlatform"
       cd "{{ openhome_folder }}/ohPlayer/."
       mkdir -p "{{ openhome_folder }}/ohPlayer/dependencies/Linux-rpi"
       cd dependencies/Linux-rpi
       # put openssl
       cp "{{ openhome_folder }}/openssl/build/openssl-development-Linux-armhf-Release.tar.bz2" .
       tar -xf openssl-development-Linux-armhf-Release.tar.bz2

       cp "{{ openhome_folder }}/ohNet/Build/Bundles/ohNet-Linux-armhf-Release.tar.gz" "."
       tar -xzf ohNet-Linux-armhf-Release.tar.gz ; mv ohNet-Linux-armhf-Release ohNet-Linux-rpi-Release

       cp "{{ openhome_folder }}/ohNetGenerated/Build/Bundles/ohNetGenerated-Linux-armhf-Release.tar.gz" "."
       tar -xzf  ohNetGenerated-Linux-armhf-Release.tar.gz; mv ohNetGenerated-Linux-armhf-Release ohNetGenerated-Linux-rpi-Release

       cp -Rf "{{ openhome_folder }}/ohPipeline/build/ohMediaPlayer.tar.gz" "."
       tar -xzf ohMediaPlayer.tar.gz

       cd ../../linux ; DISABLE_GTK=1 make raspbian

