---
# tasks file for openhome_player
- name: ansible create directory example
  ansible.builtin.file:
    path: "{{ openhome_folder }}"
    state: directory

- name: Install openssl sources
  git:
    repo: "{{ openhome_openssl_repo }}"
    dest: "{{ openhome_folder }}/openssl"
    update: no

- name: Install ohWafHelpers sources
  git:
    repo: "{{ openhome_ohwafhelpers_repo }}"
    dest: "{{ openhome_folder }}/ohWafHelpers"
    update: no

- name: Install ohTools 
  git:
    repo: "{{ openhome_ohtools_repo }}"
    dest: "{{ openhome_folder }}/ohdevtools"

- name: Install ohPlayer sources
  git:
    repo: "{{ openhome_ohplayer_repo }}"
    dest: "{{ openhome_folder }}/ohPlayer"


- name: Install ohMediaPlayer sources
  git:
    repo: "{{ openhome_ohmediaplayer_repo }}"
    dest: "{{ openhome_folder }}/ohPipeline"
    update: no

- name: Install ohNet sources
  git:
    repo: "{{ openhome_ohnet_repo }}"
    dest: "{{ openhome_folder }}/ohNet"

- name: Install ohNetGenerated sources
  git:
    repo: "{{ openhome_ohnetgenerated_repo }}"
    dest: "{{ openhome_folder }}/ohNetGenerated"

